In [1]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits
import matplotlib.pyplot as plt
digits = load_digits()

In [14]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(digits.data,digits.target,test_size=0.3)

In [15]:
# Logistic Regression

In [16]:
lr = LogisticRegression(solver='liblinear',multi_class='ovr')
lr.fit(X_train, y_train)
lr.score(X_test, y_test)

0.9574074074074074

In [ ]:
# SVM

In [17]:
svm = SVC(gamma='auto')
svm.fit(X_train, y_train)
svm.score(X_test, y_test)

0.5185185185185185

In [ ]:
# Random Forest

In [18]:
rf = RandomForestClassifier(n_estimators=40)
rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.9740740740740741

In [ ]:
# KFold cross validation
# Basic example

In [7]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)
kf 

KFold(n_splits=3, random_state=None, shuffle=False)

In [20]:
kf.split([1,2,3,4,5,6,7,8,9])

<generator object _BaseKFold.split at 0x7f7696b78e50>

In [8]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index, test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [9]:
# Use KFold for our digits example

In [10]:
def get_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)

In [21]:
get_score(LogisticRegression(), X_train, X_test,y_train,y_test)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


0.9629629629629629

In [23]:
get_score(SVC(), X_train, X_test,y_train,y_test)

0.9814814814814815

In [24]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=3)

scores_logistic = []
scores_svm = []
scores_rf = []

for train_index, test_index in folds.split(digits.data,digits.target):
    X_train, X_test, y_train, y_test = digits.data[train_index], digits.data[test_index], \
                                       digits.target[train_index], digits.target[test_index]
    scores_logistic.append(get_score(LogisticRegression(solver='liblinear',multi_class='ovr'), X_train, X_test, y_train, y_test))  
    scores_svm.append(get_score(SVC(gamma='auto'), X_train, X_test, y_train, y_test))
    scores_rf.append(get_score(RandomForestClassifier(n_estimators=40), X_train, X_test,y_train,y_test))

In [25]:
scores_logistic

[0.8948247078464107, 0.9532554257095158, 0.9098497495826378]

In [26]:
scores_svm

[0.3806343906510851, 0.41068447412353926, 0.5125208681135225]

In [27]:
scores_rf

[0.9215358931552587, 0.9449081803005008, 0.9265442404006677]

In [ ]:
# cross_val_score function

In [32]:
from sklearn.model_selection import cross_val_score

In [33]:
# Logistic regression model performance using cross_val_score

In [35]:
cross_val_score(LogisticRegression(solver='liblinear',multi_class='ovr'), digits.data, digits.target)

array([0.92222222, 0.88333333, 0.95264624, 0.95821727, 0.89415042])

In [29]:
# svm model performance using cross_val_score

In [36]:
cross_val_score(SVC(gamma='auto'), digits.data, digits.target,cv=3)

array([0.38063439, 0.41068447, 0.51252087])

In [37]:
# random forest performance using cross_val_score

In [38]:
cross_val_score(RandomForestClassifier(n_estimators=40),digits.data, digits.target,cv=3)

array([0.92654424, 0.94323873, 0.92320534])

In [ ]:
# Parameter tunning using k fold cross validation

In [39]:
scores1 = cross_val_score(RandomForestClassifier(n_estimators=5),digits.data, digits.target, cv=10)
np.average(scores1)

0.8675418994413407

In [40]:
scores2 = cross_val_score(RandomForestClassifier(n_estimators=20),digits.data, digits.target, cv=10)
np.average(scores2)

0.927653631284916

In [41]:
scores3 = cross_val_score(RandomForestClassifier(n_estimators=30),digits.data, digits.target, cv=10)
np.average(scores3)

0.9382122905027932

In [42]:
scores4 = cross_val_score(RandomForestClassifier(n_estimators=40),digits.data, digits.target, cv=10)
np.average(scores4)

0.9404562383612662