In [1]:
import numpy as np


In [2]:
y_predicted = np.array([1,1,0,0,1])
y_true = np.array([0.30,0.7,1,0,0.5])


In [3]:
# Implement Mean Absolute Error

In [9]:
def mae(y_true, y_predicted):
  total_error = 0 
  for yt, yp in zip(y_true, y_predicted):
    print(yt,yp)

In [10]:
mae(y_true, y_predicted)

0.3 1
0.7 1
1.0 0
0.0 0
0.5 1


In [14]:
def mae(y_true, y_predicted):
  total_error = 0 
  for yt, yp in zip(y_true, y_predicted):
     total_error += abs(yt-yp)
     print("Total error:", total_error)
     mae = total_error/len(y_true)
     return mae

In [15]:
mae(y_true, y_predicted)

Total error: 0.7


0.13999999999999999

In [16]:
def mae(y_predicted, y_true):
    total_error = 0
    for yp, yt in zip(y_predicted, y_true):
        total_error += abs(yp - yt)
    print("Total error is:",total_error)
    mae = total_error/len(y_predicted)
    print("Mean absolute error is:",mae)
    return mae

In [17]:
mae(y_predicted, y_true)

Total error is: 2.5
Mean absolute error is: 0.5


0.5

In [18]:
y_predicted - y_true

array([ 0.7,  0.3, -1. ,  0. ,  0.5])

In [19]:
np.abs(y_predicted - y_true)

array([0.7, 0.3, 1. , 0. , 0.5])

In [20]:
np.mean(np.abs(y_predicted - y_true))

0.5

In [21]:
np.sum(np.abs(y_predicted - y_true))

2.5

In [ ]:
# Implement same thing using numpy in much easier way

In [22]:
def mae_np(y_predicted, y_true):
    return np.mean(np.abs(y_predicted-y_true))

In [23]:
mae_np(y_predicted, y_true)

0.5

In [ ]:
#  Implement Log Loss or Binary Cross Entropy

In [24]:
np.log([0])

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([-inf])

In [25]:
np.log([0.0000000001])

array([-23.02585093])

In [40]:
epsilon = 1e-9

In [41]:
np.log([1e-12])

array([-27.63102112])

In [42]:
np.log([epsilon])

array([-20.72326584])

In [43]:
y_predicted

array([1, 1, 0, 0, 1])

In [44]:
y_predicted_new = [max(i,epsilon) for i in y_predicted]
y_predicted_new

[1, 1, 1e-09, 1e-09, 1]

In [45]:
1-epsilon

0.999999999

In [46]:
y_predicted_new = [min(i,1-epsilon) for i in y_predicted_new]
y_predicted_new

[0.999999999, 0.999999999, 1e-09, 1e-09, 0.999999999]

In [48]:
y_predicted_new = np.array(y_predicted_new)

In [49]:
np.log(y_predicted_new)

array([-9.99999972e-10, -9.99999972e-10, -2.07232658e+01, -2.07232658e+01,
       -9.99999972e-10])

In [50]:
-np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

10.361632927457785

In [51]:
def log_loss(y_true, y_predicted):
    y_predicted_new = [max(i,epsilon) for i in y_predicted]
    y_predicted_new = [min(i,1-epsilon) for i in y_predicted_new]
    y_predicted_new = np.array(y_predicted_new)
    return -np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

In [52]:
log_loss(y_true, y_predicted)

10.361632927457785